version: '3.8'

services:
  anyforms-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anyforms-back
    ports:
      - "8090:8090"
    env_file:
      - .env

    # Лимит контейнера по памяти — 512 МБ
    mem_limit: 512m

    restart: unless-stopped
    networks:
      - anyforms-network

networks:
  anyforms-network:
    driver: bridge
