version: '3.8'

services:
  anyforms-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anyforms-back
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - anyforms-network

volumes:
  postgres_data:

networks:
  anyforms-network:
    driver: bridge

